//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPStoreManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.SaleItems = new HashSet<SaleItem>();
        }
    
        public int ProductID { get; set; }
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Stock { get; set; }
        public decimal Price { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<SaleItem> SaleItems { get; set; }
    }
}
